{
  "name":"Vermont Center for Ecostudies",
  "acronym":"VCE",
  "uid":"dp0",
  "guid":null,
  "address":null,
  "phone":null,
  "email":null,
  "pubShortDescription":null,
  "pubDescription":null,
  "techDescription":null,
  "focus":null,
  "state":null,
  "websiteUrl":"http://ipt.vtecostudies.org",
  "alaPublicUrl":"https://collectory.vtatlasoflife.org/public/show/dp0",
  "networkMembership":null,
  "attributions":[],
  "dateCreated":"2019-10-07T15:01:53Z",
  "lastUpdated":"2019-10-07T17:34:42Z",
  "userLastModified":"jloomis@vtecostudies.org",
  "dataResources":[
    {"name":"Records of Hawk Moths (Sphingidae) from Vermont, USA",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr410",
    "uid":"dr410",
    "id":430},
    {"name":"Lady Beetle (Coccinellidae) Records Comprising the Checklist of Vermont Species",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr413",
    "uid":"dr413",
    "id":433},
    {"name":"Carabidae of Vermont and New Hampshire",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr412",
    "uid":"dr412",
    "id":432},
    {"name":"Records of Giant Silkmoths (Saturniinae) from Vermont Collections and 2002-2007",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr415",
    "uid":"dr415",
    "id":435},
    {"name":"Checklist of Vermont Mammals",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr414",
    "uid":"dr414",
    "id":434},
    {"name":"Checklist of Crickets and Katydids of Vermont, USA",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr416",
    "uid":"dr416",
    "id":436},
    {"name":"Vermont Buprestidae Survey",
    "uri":"https://collectory.vtatlasoflife.org/ws/dataResource/dr411",
    "uid":"dr411",
    "id":431}
  ],
  "gbifRegistryKey":null
}
